### ISSUE TITLE
Add more restricted profane words

### ISSUE THREAD

**Issue by Samasaur1** [Samasaur1/CityManagement#10]
In [Utilities.java](https://github.com/Samasaur1/CityManagement/blob/master/src/main/java/com/samgauck/CityManagement/Utilities.java) line 59, there is a `HashSet<String>` of profane words. Any contributions are appreciated. Just follow the same format.

**Comment by raduandrone** [comment]
Hi, do you mind if I have a look at this?

**Comment by Samasaur1** [comment]
Sorry for not responding, my notifications stopped working. Thanks for helping out!

**Comment by Samasaur1** [comment]
I'm leaving this open in case anyone else decides to list more words

**Comment by Samasaur1** [comment]
Transferring this issue [here](https://github.com/Samasaur1/Utilities/issues/1), in the Utilities repository, as the Utilities code has been moved there
